logging:
  level: INFO
  path: ./logs

paths:
  outcome: TEST_OUTCOME.csv

data:
  type: "finetune"
  truncation_len: 30
  min_len: 2 # 0 by default

outcome: # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_censoring: -10 # censor time after index date (negative means before)
  n_hours_start_follow_up: 1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: null # end follow up (considering outcomes) time after index date (negative means before)
