name: "Setup Python + virtual environment"
description: "Sets up Python and pip cache, creates a fresh venv, and installs deps quickly."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip

    - name: Create & activate venv
      shell: bash
      run: |
        python -m venv .venv
        echo ".venv/bin" >> $GITHUB_PATH
        source .venv/bin/activate

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt