name: "Setup Python + virtual environment"
description: "Sets up Python and caches venv for faster execution"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip

    - name: Cache virtual environment
      uses: actions/cache@v3
      id: venv-cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-python-3.10-${{ hashFiles('requirements.txt') }}

    - name: Create & activate venv
      shell: bash
      if: steps.venv-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment path
      shell: bash
      run: |
        echo ".venv/bin" >> $GITHUB_PATH