logging:
  level: INFO
  path: ./logs
  
data:
  dataset:
    select_ratio: .30
    masking_ratio: .8
    replace_ratio: .1
    ignore_special_tokens: true
  val_ratio: 0.2

trainer_args:
  batch_size: 256
  effective_batch_size: 512
  epochs: 3
  info: true
  sampler: null
  gradient_clip: 
    clip_value: 1.0
  shuffle: true
  early_stopping: null 
  num_workers: 1
  compile: false


model:
  hidden_size: 96
  intermediate_size: 192
  num_hidden_layers: 6
  num_attention_heads: 6
  max_position_embeddings: 512 
  type_vocab_size: 1000
  embedding_dropout: 0.1 
  
  
optimizer:
  lr: 5e-4
  eps: 1e-6

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  num_warmup_epochs: 1
  num_training_epochs: 1

metrics:
  top1:
    _target_: corebehrt.modules.monitoring.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: corebehrt.modules.monitoring.metrics.PrecisionAtK

    topk: 10
  mlm_loss:
    _target_: corebehrt.modules.monitoring.metrics.LossAccessor
    loss_name: loss

