logging:
  level: INFO
  path: ./logs

paths:
  outcome: "breast_cancer.csv"

selection:
  exclude_prior_outcomes: false 
  exposed_only: false 
  age:
    min_years: 0 
    max_years: 120 
  categories: 
    GENDER: 
      include: [Kvinde] 

index_date: 
  mode: relative 
  absolute: 
    year: 2022
    month: 1
    day: 1
  relative: 
    n_hours_from_exposure: -2190 

cv_folds: 1 
test_ratio: 0.1 
