logging:
  level: INFO
  path: ./logs

paths:
  splits: [ tuning ]

outcomes:
  breast_cancer:
    type: [ code ]
    match: [ [ 'DC50', 'DD05' ] ]
    match_how: startswith
    case_sensitive: false
