logging:
  level: INFO
  path: ./logs

paths:
  outcome: "breast_cancer.csv"
  
data:
  type: "finetune"
  truncation_len: 512
  min_len: 0

outcome:
  n_hours_censoring: -2190
  n_hours_start_follow_up: 1
  n_hours_end_follow_up: null 
