logging:
  level: INFO
  path: ./outputs/logs

paths:
  data: ./example_data/example_MEDS_data_wo_held_out
  tokenized: ./outputs/tokenized_wo_held_out
  features: ./outputs/features_wo_held_out
  
features:
  values:
    value_creator_kwargs:
      num_bins: 100

tokenizer:
  sep_tokens: true
  cls_token: true
  cutoffs:
   D: 3 # diagnosis
   M: 4 # medication

excluder:
  min_age: -1
  max_age: 120