logging:
  level: INFO
  path: ./outputs/logs

paths:
  model: "./outputs/xgboost"
  folds_dir: "./outputs/finetuning/processed_data"
  test_data_dir: "./outputs/testing/held_out/processed_data" 
  run_name: "evaluate"

  predictions: "./outputs/testing/held_out/xgboost_predictions"

return_feature_importance:
  importance_type: "gain"

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score
  pr_auc: 
    _target_: sklearn.metrics.average_precision_score