env: local

paths:
  model_path: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test"
  run_name: "evaluate"

metrics:
  accuracy:
    _target_: corebehrt.modules.monitoring.metrics.Accuracy
    threshold: 0.6
  balanced_accuracy:
    _target_: corebehrt.modules.monitoring.metrics.Balanced_Accuracy

  precision:
    _target_: corebehrt.modules.monitoring.metrics.Precision
  recall:
    _target_: corebehrt.modules.monitoring.metrics.Recall

  roc_auc:
    _target_: corebehrt.modules.monitoring.metrics.ROC_AUC
  pr_auc:
    _target_: corebehrt.modules.monitoring.metrics.PR_AUC


data:
  min_len: 1
  test_data_dir: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test" 
