logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  prepared_data: ./outputs/pretraining/processed_data/
  # restart_model: ... # Use for restarting from checkpoint

## OUTPUTS
  model: ./outputs/pretraining # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder
  
data:
  dataset:
    select_ratio: 1.
    masking_ratio: .8
    replace_ratio: .1
    ignore_special_tokens: true


trainer_args:
  batch_size: 32
  effective_batch_size: 64
  epochs: 1
  info: true
  sampler: null
  gradient_clip: 
    clip_value: 1.0
  shuffle: true
  early_stopping: null # num_epochs or null/false

model:
  hidden_size: 96
  num_hidden_layers: 3
  num_attention_heads: 3
  intermediate_size: 64
  
  type_vocab_size: 1024 # !!! type_vocab_size should be > truncation_len//2 if sep token else >truncation len
  embedding_dropout: 0.1 
  max_position_embeddings: 512 # the longest sequence length we will use this model with
  age_scale: 1e-2 # 100 -> 1
  abspos_scale: 1e-5 # 400k -> 4
  age_shift: -50 # center around 0
  abspos_shift: -90_000 # 0 will be around 2015
  
  is_causal: true  
  
optimizer:
  lr: 5e-4
  eps: 1e-6

scheduler:
  _target_: transformers.get_linear_schedule_with_warmup
  num_warmup_epochs: 2
  num_training_epochs: 3

metrics:
  top1:
    _target_: corebehrt.modules.monitoring.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: corebehrt.modules.monitoring.metrics.PrecisionAtK

    topk: 10
  mlm_loss:
    _target_: corebehrt.modules.monitoring.metrics.LossAccessor
    loss_name: loss
