logging:
  level: INFO
  path: ./outputs/logs

paths:
  model: "./outputs/finetuning/xgboost"
  folds_dir: "./outputs/finetuning/processed_data/good"
  test_data_dir: "./outputs/testing/held_out/processed_data/good" 
  run_name: "evaluate"

  predictions: "./outputs/testing/held_out/xgboost_predictions"

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score
  pr_auc: 
    _target_: sklearn.metrics.average_precision_score

save_info: 
  sequence_length: 
    _target_: corebehrt.main.helper.evaluate_finetune.get_sequence_length