logging:
  level: INFO
  path: ./outputs/logs

paths:
  ## INPUTS
  features: ./outputs/features
  tokenized: ./outputs/tokenized
  cohort: ./outputs/cohort/finetune_test/ # path to cohort directory
  outcomes: ./outputs/outcomes
  outcome: TEST_OUTCOME.csv

  ## OUTPUTS
  prepared_data: ./outputs/finetuning/processed_data/good/ # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

data:
  type: "finetune"
  truncation_len: 30
  min_len: 1 # 0 by default

outcome:
  # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_censoring: -10 # censor time after index date (negative means before)
  n_hours_start_follow_up: -1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: null # end follow up (considering outcomes) time after index date (negative means before)
