logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  prepared_data: ./outputs/finetuning/processed_data/good/
## OUTPUTS
  model: ./outputs/finetuning/xgboost # Save model/outputs to this folder  

model:
  objective: binary:logistic
  eval_metric: auc
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 1
  gamma: 0
  seed: 42

trainer_args:
  early_stopping_rounds: 10
  num_boost_round: 100
  verbose_eval: False

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score
  pr_auc: 
    _target_: sklearn.metrics.average_precision_score  