name: Docstring Coverage Badge

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  doc-coverage:
    name: Docstring Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install docstr-coverage

      - name: Run docstring coverage check
        id: extract
        continue-on-error: true  # Move to step level
        run: |
          DOC_COV=$(docstr-coverage corebehrt -p --skip-magic --skip-init | awk '{print int($1)}')
          echo "Docstring coverage: ${DOC_COV}%"
          echo "doccov=${DOC_COV}" >> $GITHUB_OUTPUT

      - name: Create Dynamic Coverage Badge
        if: always()  # Always try to create badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: b02ecb317ea24a8ced5e72ae96e1c0c3
          filename: docstr-coverage.json
          label: Docstr Coverage
          message: "${{ steps.extract.outputs.doccov || '0' }}%"
          valColorRange: "${{ steps.extract.outputs.doccov || '0' }}"
          minColorRange: 40
          maxColorRange: 100

      - name: Report Status
        if: always()  # Always report status
        shell: bash
        run: |
          if [[ "${{ steps.extract.outputs.doccov }}" != "" ]]; then
            echo "✅ Docstring coverage check completed successfully"
            exit 0
          else
            echo "⚠️ Docstring coverage check failed but continuing"
            exit 0
          fi
