name: Run Tests and Generate Dynamic Coverage Badge

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run Tests with Coverage
        run: |
          # Run tests and generate a terminal report
          coverage run --omit=_remote_module_non_scriptable.py -m unittest discover
          coverage report

      - name: Get Coverage Percentage
        id: get_coverage
        run: |
          # Extract the overall coverage percentage from the coverage report
          # This assumes your report contains a TOTAL line, e.g.:
          # TOTAL    100    0   100%
          COVERAGE=$(coverage report | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage is ${COVERAGE}%"

      - name: Create Dynamic Coverage Badge via Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}       # Your secret token with the gist scope
          gistID: b02ecb317ea24a8ced5e72ae96e1c0c3                  # Fill in your gist id here
          filename: coverage.json                 # Use coverage.svg if you prefer SVG mode
          label: Coverage
          message: "${{ steps.get_coverage.outputs.coverage }}%"
          valColorRange: "${{ steps.get_coverage.outputs.coverage }}"
          maxColorRange: 100
          minColorRange: 0
          style: flat