name: Run Tests and Generate Coverage Badge

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage coverage-badge

      - name: Run Tests with Coverage
        run: |
          coverage run --omit=_remote_module_non_scriptable.py -m unittest discover
          coverage report

      - name: Generate Coverage Badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Commit Coverage Badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add coverage.svg
          git diff --cached --quiet || git commit -m "Update coverage badge"
      - name: Push Coverage Badge
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg