name: Unittest

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: "Run Unit Tests"
        run: |
          python -m unittest discover

      - name: "Run Coverage and Generate Report"
        run: |
          coverage run --omit=_remote_module_non_scriptable.py -m unittest discover
          coverage report > coverage.txt
      
      - name: "Extract Total Coverage"
        id: extract
        run: |
          total=$(grep TOTAL coverage.txt | awk '{print $4}' | sed 's/%//')
          echo "Total coverage: $total%"
          echo "total=$total" >> $GITHUB_OUTPUT

      - name: Create Dynamic Coverage Badge via Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}       # Your secret token with the gist scope
          gistID: b02ecb317ea24a8ced5e72ae96e1c0c3                  # Fill in your gist id here
          filename: covbadge.json
          label: Coverage
          message: "${{ steps.extract.outputs.total }}%"
          valColorRange: "${{ steps.extract.outputs.total }}"
          minColorRange: 0
          maxColorRange: 100


